[telegram]
userbot = true
# Get your telegram api-key from @botfather
api_key = "your_telegram_api_key (empty if in userbot mode)"
phone_number = "your_phone_number (empty if not in userbot mode)"
# Get client api keys from https://my.telegram.org
app_api_id = 0
app_api_hash = "apihash"

[database]
sql_uri = "sqlite:///data/archivebot.sqlite"

[logging]
sentry_enabled = false
sentry_token = ""

[download]
# Default for downloaded files
allowed_types = [
    "document",
    "photo",
]
target_dir = "./data/"
